# Generated by Django 5.0.7 on 2026-09-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_distance', models.FloatField(help_text='Known real-world distance in meters')),
                ('depth_value', models.FloatField(help_text='Raw MiDaS depth value observed at that distance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['reference_distance'],
            },
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=64)),
                ('confidence', models.FloatField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
